repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]


#repos:
#  - repo: https://github.com/psf/black
#    rev: 24.4.0
#    hooks:
#      - id: black
#        language_version: python3
#        files: ^src/.*\.py$

#  - repo: https://github.com/charliermarsh/ruff-pre-commit
#    rev: v0.4.0
#    hooks:
#      - id: ruff
#        files: ^src/.*\.py$

#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.5.0
#    hooks:
#      - id: trailing-whitespace
#        files: ^src/.*\.py$
#      - id: end-of-file-fixer
#        files: ^src/.*\.py$
